// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynukrzdwbubjngfpkzea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludWtyemR3YnViam5nZnBremVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzgyOTgsImV4cCI6MjA2NDM1NDI5OH0.n5xNuRZLz4j2_MhlOV2VkWJMcuD5O0gb8L8z5fIQeWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);